
var abi = /* you have to specify the ABI that is generated by the compiler in here*/;
var ContractA = web3.eth.contract(abi);
var contractA = ContractA.at( /* deployed address of the contract*/);
var event = contractA.LogDetails();
// Now we need to watch for changes in the contract
event.watch(function(error, result){
    // Other javascript logic goes here
    if (!error)
        console.log(result);
});
// Or pass a callback to start watching immediately
// If we need to start the watching immediately, we can pass the
callback as follows
var event = contractA.LogDetails(function(error, result) {
    if (!error)
        console.log(result);
});
